[package]
name = "sycamore-macro"
categories = ["gui", "wasm", "web-programming"]
description = "A VDOM-less web library with fine grained reactivity"
edition = "2021"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version = "0.8.0-beta.1"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
proc-macro2 = "1.0.36"
quote = "1.0.15"
syn = { version = "1.0.86", features = ["extra-traits", "full"] }

[dev-dependencies]
sycamore = { path = "../sycamore", features = ["experimental-hydrate"] }
trybuild = "1.0.55"

[features]
default = []
experimental-hydrate = []
ssr = []
