[package]
name = "sycamore-macro"
categories = ["gui", "wasm", "web-programming"]
description = "proc-macro crate for Sycamore"
edition = "2021"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version.workspace = true

[lib]
proc-macro = true

[dependencies]
once_cell = "1.16.0"
proc-macro2 = "1.0.47"
quote = "1.0.21"
rand = "0.8.5"
syn = { version = "2.0.10", features = ["extra-traits", "full"] }
sycamore-view-parser = { path = "../sycamore-view-parser", version = "0.9.0-beta.3" }

[dev-dependencies]
sycamore = { path = "../sycamore", features = ["suspense"] }
trybuild = "1.0.71"

[features]
default = []
