[package]
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
categories = ["gui", "wasm", "web-programming"]
description = "A VDOM-less web library with fine grained reactivity"
edition = "2018"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
name = "sycamore-macro"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version = "0.7.1"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = "1.0.81"

[dev-dependencies]
sycamore = { path = "../sycamore", features = ["experimental-hydrate"] }
trybuild = "1.0.52"

[features]
default = []
experimental-hydrate = []
ssr = []
