[package]
name = "sycamore-macro"
categories = ["gui", "wasm", "web-programming"]
description = "proc-macro crate for sycamore"
edition = "2021"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version = "0.8.0-beta.3"

[lib]
proc-macro = true

[dependencies]
once_cell = "1.10.0"
proc-macro2 = "1.0.36"
quote = "1.0.15"
syn = { version = "1.0.86", features = ["extra-traits", "full"] }

[dev-dependencies]
sycamore = { path = "../sycamore", features = ["experimental-hydrate"] }
trybuild = "1.0.56"

[features]
default = []
experimental-hydrate = []
ssr = []
