[package]
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
edition = "2018"
name = "todomvc"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
log = "0.4.14"
sycamore = {path = "../../packages/sycamore", features = ["serde"]}
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
uuid = { version = "0.8.2", features = ["v4", "wasm-bindgen", "serde"] }
wasm-bindgen = "0.2.78"

[dependencies.web-sys]
features = ["InputEvent", "KeyboardEvent", "Location", "Storage"]
version = "0.3.55"
