[package]
name = "sycamore-view-parser"
categories = ["gui", "wasm", "web-programming"]
description = "parser for Sycamore view syntax"
edition = "2021"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version.workspace = true

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = { version = "2.0.10", features = ["extra-traits", "full"] }


[lints]
workspace = true
