[package]
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
categories = ["gui", "wasm", "web-programming"]
description = "Router for sycamore"
edition = "2018"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
name = "sycamore-router-macro"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version = "0.6.3"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
proc-macro2 = "1.0.32"
quote = "1.0.10"
syn = "1.0.81"
unicode-xid = "0.2.2"

[dev-dependencies]
expect-test = "1.1.0"
sycamore-router = { path = "../sycamore-router" }
trybuild = "1.0.52"
