[package]
categories = ["gui", "wasm", "web-programming"]
description = "proc-macro crate for sycamore-router"
edition = "2021"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
name = "sycamore-router-macro"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version = "0.8.0"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = "1.0.102"
unicode-xid = "0.2.4"

[dev-dependencies]
expect-test = "1.4.0"
sycamore-router = { path = "../sycamore-router" }
trybuild = "1.0.71"
