[package]
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
categories = ["gui", "wasm", "web-programming"]
description = "proc-macro crate for sycamore-router"
edition = "2021"
homepage = "https://github.com/sycamore-rs/sycamore"
keywords = ["wasm", "gui", "reactive"]
license = "MIT"
name = "sycamore-router-macro"
readme = "../../README.md"
repository = "https://github.com/sycamore-rs/sycamore"
version = "0.8.0-beta.2"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
proc-macro2 = "1.0.36"
quote = "1.0.15"
syn = "1.0.86"
unicode-xid = "0.2.2"

[dev-dependencies]
expect-test = "1.2.2"
sycamore-router = { path = "../sycamore-router" }
trybuild = "1.0.55"
