[package]
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
edition = "2018"
name = "maple-core"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maple-core-macro = {path = "../maple-core-macro"}
wasm-bindgen = "0.2.71"

[dependencies.web-sys]
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Window",
]
version = "0.3.48"
