[package]
authors = ["Luke Chu <37006668+lukechu10@users.noreply.github.com>"]
description = "A VDOM-less web library with fine grained reactivity"
edition = "2018"
homepage = "https://github.com/lukechu10/maple"
license = "MIT"
name = "maple-core"
readme = "../README.md"
repository = "https://github.com/lukechu10/maple"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maple-core-macro = {path = "../maple-core-macro", version = "0.1.0"}
wasm-bindgen = "0.2.71"

[dependencies.web-sys]
features = [
  "Document",
  "Element",
  "HtmlElement",
  "Node",
  "Text",
  "Window",
]
version = "0.3.48"
